# Generated by Django 5.2 on 2025-05-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rayshistorymod',
            name='rays_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
