# Generated by Django 6.0.5 on 2026-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rayshistoryproduct',
            name='price',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
