# Generated by Django 6.0.3 on 2026-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0002_rayshistorymod_rays_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='passport_photo',
            new_name='passport_photo_back',
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_photo_front',
            field=models.ImageField(blank=True, default='defaults/furgon_default.avif', null=True, upload_to='passport_photos/'),
        ),
    ]
