# Generated by Django 6.0.3 on 2026-03-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0003_rename_passport_photo_customuser_passport_photo_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
