# Generated by Django 6.0.3 on 2026-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_main', '0004_alter_customuser_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rayshistorymod',
            name='driver_expense',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raysmod',
            name='driver_expense',
            field=models.BigIntegerField(default=0),
        ),
    ]
